# Copyright (c) 2025 HPMicro
#
# SPDX-License-Identifier: BSD-3-Clause

SOC_FLASH_0_ID=0
CONFIG_FLASH_BASE_ADDRESS=0x80000000
CONFIG_BOOT_WATCHDOG_FEED=0
HPM_PAGE_LAYOUT_NONE_ID=0
HPM_PAGE_LAYOUT_NONE_START_OFFSET=0
HPM_PAGE_LAYOUT_NONE_SIZE=0x400
HPM_PAGE_LAYOUT_NONE_END_OFFSET=0
HPM_PAGE_LAYOUT_NONE_PAGES_SIZE=1024
HPM_PAGE_LAYOUT_NONE_PAGES_COUNT=1
MCUBOOT_IMAGE_TRAILER_SIZE=0x1000
MCUBOOT_IMAGE_HEADER_SIZE=0x200

FLASH_SIZE=16M
CONFIG_BOOTLOADER_SIZE=0x40000
BOOTLOADER_OFFSET=0x3000
MCUBOOT_IMAGE0_PRIMARY_START_ADDRESS=0x00043000
MCUBOOT_APPLICATION_SIZE=0x7C0000
MCUBOOT_IMAGE0_SECONDARY_START_ADDRESS=0x803000
MCUBOOT_SCRATCH_OFFSET=0xFC3000
MCUBOOT_SCRATCH_SIZE=0x3d000

HPM_PAGE_LAYOUT_NOR_CFG_ID=1
HPM_PAGE_LAYOUT_NOR_CFG_START_OFFSET=0x400
HPM_PAGE_LAYOUT_NOR_CFG_SIZE=0xC00
HPM_PAGE_LAYOUT_NOR_CFG_END_OFFSET=0x1000
HPM_PAGE_LAYOUT_NOR_CFG_PAGES_SIZE=1024
HPM_PAGE_LAYOUT_NOR_CFG_PAGES_COUNT=3

HPM_PAGE_LAYOUT_BOOT_PARAM_ID=2
HPM_PAGE_LAYOUT_BOOT_PARAM_START_OFFSET=0x1000
HPM_PAGE_LAYOUT_BOOT_PARAM_SIZE=0xC00
HPM_PAGE_LAYOUT_BOOT_PARAM_END_OFFSET=0x2000
HPM_PAGE_LAYOUT_BOOT_PARAM_PAGES_SIZE=1024
HPM_PAGE_LAYOUT_BOOT_PARAM_PAGES_COUNT=8

HPM_PAGE_LAYOUT_MCUBOOT_ID=3
HPM_PAGE_LAYOUT_MCUBOOT_START_OFFSET=0x3000
HPM_PAGE_LAYOUT_MCUBOOT_SIZE=0x40000
HPM_PAGE_LAYOUT_MCUBOOT_END_OFFSET=0x43000
HPM_PAGE_LAYOUT_MCUBOOT_PAGES_SIZE=4096
HPM_PAGE_LAYOUT_MCUBOOT_PAGES_COUNT=64

HPM_PAGE_LAYOUT_IMAGE0_SLOT0_ID=4
HPM_PAGE_LAYOUT_IMAGE0_SLOT0_START_OFFSET=0x43000
HPM_PAGE_LAYOUT_IMAGE0_SLOT0_SIZE=0x7C0000
HPM_PAGE_LAYOUT_IMAGE0_SLOT0_END_OFFSET=0x803000
HPM_PAGE_LAYOUT_IMAGE0_SLOT0_PAGES_SIZE=32768
HPM_PAGE_LAYOUT_IMAGE0_SLOT0_PAGES_COUNT=248

HPM_PAGE_LAYOUT_IMAGE0_SLOT1_ID=5
HPM_PAGE_LAYOUT_IMAGE0_SLOT1_START_OFFSET=0x803000
HPM_PAGE_LAYOUT_IMAGE0_SLOT1_SIZE=0x7C0000
HPM_PAGE_LAYOUT_IMAGE0_SLOT1_END_OFFSET=0xFC3000
HPM_PAGE_LAYOUT_IMAGE0_SLOT1_PAGES_SIZE=32768
HPM_PAGE_LAYOUT_IMAGE0_SLOT1_PAGES_COUNT=248

HPM_PAGE_LAYOUT_SCRATCH_ID=6
HPM_PAGE_LAYOUT_SCRATCH_START_OFFSET=0xFC3000
HPM_PAGE_LAYOUT_SCRATCH_SIZE=0x3d000
HPM_PAGE_LAYOUT_SCRATCH_END_OFFSET=0x1000000
HPM_PAGE_LAYOUT_SCRATCH_PAGES_SIZE=4096
HPM_PAGE_LAYOUT_SCRATCH_PAGES_COUNT=61

